# Generated by Django 2.0.4 on 2018-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('idGame', models.AutoField(primary_key=True, serialize=False)),
                ('colorCode', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
