# Generated by Django 2.0.4 on 2018-04-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemaker', '0003_auto_20180429_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='createdAt',
        ),
    ]
